---
title: "Step_change"
output: html_document
---

```{r}

library(dplyr)

leopardseal_mp_steps <- leopardseal_mp_steps %>%
  arrange(id, date)

# looking for biggest change in tra rate 

#difference til next step
change <- data.frame(diff(leopardseal_mp_steps$step_length_km))
#saveRDS(change, "change.rds")

# add to df
leopardseal_mp_steps$change <- c(diff(leopardseal_mp_steps$step_length_km), NA)

tracks_b <- merge(
  tracks_b,
  leopardseal_mp_steps[, c("id", "lon","lat", "change")],
  by = c("id", "lon", "lat"),
  all.x = TRUE)

#saveRDS(tracks_b, "tracks_b.rds")


hist(change[[1]],  breaks = 100)
lines(density(na.omit(change[[1]])), col = "red", lwd = 2)

#kernel
hist(change[[1]], breaks = 100, freq = FALSE,main = "Histogram of change") 
lines(density(na.omit(change[[1]])), col = "red", lwd = 2)
axis(1, at = seq(floor(min(change[[1]], na.rm = TRUE)),
                 ceiling(max(change[[1]], na.rm = TRUE)),
                 by = 5))


```

Plot with tracks 
```{r}
library(rnaturalearth)
library(ggplot2)
library(sf)

bg <- ne_countries(scale = "large",returnclass = "sf")
bb <- st_bbox(tracks_b) 

ggplot() +
  geom_sf(data = bg) +
  geom_sf(data = tracks_b , aes(colour=change)) +
  coord_sf(
    xlim = c(bb["xmin"], bb["xmax"]),
    ylim = c(bb["ymin"], bb["ymax"])) +
  scale_colour_viridis_c()

ggplot() +
  geom_sf(data = bg) +
  geom_sf(data = tracks_b[tracks_b$id == 173717, ] , aes(colour=change)) +
  coord_sf(
    xlim = c(bb["xmin"], bb["xmax"]),
    ylim = c(bb["ymin"], bb["ymax"])) +
  scale_colour_viridis_c()

#binary 
tracks_b$change_bin <- ifelse(tracks_b$change > 12, 1, 0)

#for one
ggplot() +
  geom_sf(data = bg) +
  geom_sf(data = tracks_b[tracks_b$id == 173717, ] , aes(colour=change_bin)) +
  coord_sf(
    xlim = c(bb["xmin"], bb["xmax"]),
    ylim = c(bb["ymin"], bb["ymax"]))

#for all
ggplot() +
  geom_sf(data = bg) +
  geom_sf(data = tracks_b , aes(colour=change_bin)) +
  coord_sf(
    xlim = c(bb["xmin"], bb["xmax"]),
    ylim = c(bb["ymin"], bb["ymax"]))


```

```{r}

ggplot() +
  geom_sf(data = bg) +
  geom_sf(data = tracks_b[tracks_b$id == 173717, ] , aes(colour=change_bin)) +
  coord_sf(
    xlim = c(bb["xmin"], bb["xmax"]),
    ylim = c(bb["ymin"], bb["ymax"]))

```

